version: '3.1'

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: eric
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: pgdb
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    user: "999:999"
    privileged: true
